### ISSUE TITLE
False positive: name ALWAYS assumed to be SQL keyword

### ISSUE THREAD

**Issue by mcandre** [Trevoke/sqlup-mode.el#29]
In many contexts, `name` is not actually a SQL keyword, but sqlup-mode always treats it as one.

Example:

    INSERT INTO roles(create_timestamp, name, description)

is incorrectly sqlup'ed to

    INSERT INTO roles(create_timestamp, NAME, description)

**Comment by Trevoke** [comment]
Thanks for opening the issue. I've noticed that as well; I don't currently know how to fix that. 

Do you know in *which* contexts `name` is *not* a keyword?

The current `sqlup` implementation drops down to emacs' `sql-mode` and relies on `sql-mode` to determine what is and isn't a keyword.

For instance, I just did a quick Google search for postgres keywords and found this:

> In Table C-1 in the column for PostgreSQL we classify as "non-reserved" those key words that are explicitly known to the parser but are allowed as column or table names. Some key words that are otherwise non-reserved cannot be used as function or data type names and are marked accordingly. (Most of these words represent built-in functions or data types with special syntax. The function or type is still available but it cannot be redefined by the user.) Labeled "reserved" are those tokens that are not allowed as column or table names. Some reserved key words are allowable as names for functions or data types; this is also shown in the table. If not so marked, a reserved key word is only allowed as an "AS" column label name.

http://www.postgresql.org/docs/current/static/sql-keywords-appendix.html

In the Postgres docs, `name` is marked as known to be a keyword but allowed to be a column name as well.

I've kept the implementation fairly small so far, and I admit I'm shying away from the idea of writing a much more complex and context-sensitive parser. Maybe this should be reflected as a bug in `sql-mode` ?

(alternatively, ideas for more band-aid level fixes are welcome :) )

**Comment by Trevoke** [comment]
I have two ideas for fixing this:

1. Allow for a list of exceptions (words to treat as non-keywords)
2. Treat this as a special case and figure out when it shouldn't be upper-cased, e.g. "between SELECT and FROM" or "after INSERT INTO tablename("

Not super happy about either right now, but I have nothing else.

**Comment by dakra** [comment]
I would be fine with only solution 1.
I never use `name` and if I should I can just capitalize it myself.

It would also be good if a `.` wouldn't split the word,
now `select users.name from users` becomes `SELECT users.NAME FROM users`

**Comment by Trevoke** [comment]
That works for me; after all, this is what version pre-1.0 are for.. Experimenting.
