### ISSUE TITLE
sqlup-mode does not up-case word after pressing return key

### ISSUE THREAD

**Issue by atofigh** [Trevoke/sqlup-mode.el#31]
I believe there is a bug in this function:

```lisp
(defun sqlup-user-pressed-returnp ()
  (and (> 0 (length (this-command-keys-vector)))
       (equal 13 (elt (this-command-keys-vector) 0))))
```

This checks if the length of `this-command-keys-vector` is **less** than zero. Also, I think the function should accept `\n` (value 10) here in addition to `\r` (value 13). I know almost no elisp, but what about something like:

```lisp
(defun sqlup-user-pressed-returnp ()
  (and (< 0 (length (this-command-keys-vector)))
       (or (equal 13 (elt (this-command-keys-vector) 0))
           (equal 10 (elt (this-command-keys-vector) 0)))))
```

**Comment by Trevoke** [comment]
You're absolutely right. I would accept your fix. Do you want to open a pull request?

**Comment by atofigh** [comment]
Sure. Sent a pull request your way.

It is a great mode to have by the way. Thanks for making it available.

/ali

**Comment by Trevoke** [comment]
Thanks for the PR :)

And glad to make people happy with this. It was my very first emacs-lisp work.. And it was really good to get me going.
