### ISSUE TITLE
Add function 

### ISSUE THREAD

**Issue by ReneFroger** [Trevoke/sqlup-mode.el#37]
Thanks for sharing this awesome package! However, I have a little question. I discovered the function [sql-indent-string](http://stackoverflow.com/questions/24397274/writing-php-with-sql-queries-in-emacs/24659949#24659949) and I would like to work it in pair with the `sqlup-mode`. 

However, the `sqlup-capitalize-keywords-in-region` requires a region to work with it. So I'm
wondering if there could be function added that upcase the contents of entire
existing buffer? I would greatly appreciate it.

If so, then I could implement the function for the entire buffer into the `sql-indent-string`.

**Comment by Trevoke** [comment]
Would it be reasonable if the function took an optional start and end -- and acted on the entire buffer otherwise?

**Comment by ReneFroger** [comment]
Nevermind, I got it solved in the other way: http://emacs.stackexchange.com/questions/19002/how-align-tabs-inside-block-of-string

But I really appreciate your thought in this, thanks for that!

**Comment by Trevoke** [comment]
Glad to hear it and thanks for the link :)
