### ISSUE TITLE
Support NoSQL databases like Redis, MongoDB etc

### ISSUE THREAD

**Issue by stardiviner** [Trevoke/sqlup-mode.el#39]
as the title said.
I found Emacs ELPA has package called `redis.el`
https://github.com/emacs-pe/redis.el

It has a mode called `reids-mode` for editing commands.
I hope sqlup-mode can support them.

**Comment by Trevoke** [comment]
Hi,

Thanks for the feature request. I see that `redis.el` has a list of keywords in the mode. Since I was able to leverage emacs' built-in `sql.el`, this should be doable.

**Comment by stardiviner** [comment]
That's great.

**Comment by stardiviner** [comment]
Any progress on this?

**Comment by Trevoke** [comment]
I added support for `redis-mode`. We can take a look at renaming the mode later when there's a third or fourth request for other capitalization that gets implemented :)

**Comment by Trevoke** [comment]
Let me know if it works well for you.

**Comment by stardiviner** [comment]
I got error:
```
Error in post-command-hook (sqlup-capitalize-as-you-type): (void-function sqlup-keywordp)
```

**Comment by stardiviner** [comment]
https://github.com/Trevoke/sqlup-mode.el/pull/40

**Comment by stardiviner** [comment]
After fix this, it works now.
