### ISSUE TITLE
Testing for eval strings shouldn't be done with a global var

### ISSUE THREAD

**Issue by yogsothoth** [Trevoke/sqlup-mode.el#45]
sqlup tries to test whether a given string is just a bare string or an eval string, containing SQL code to feed to things like EXECUTE.
The current implementation keeps track of that using a global var, which in addition to not being very clean, probably breaks when working across multiple SQL buffers.
The code should be revised to keep the analysis buffer-local.

**Comment by yogsothoth** [comment]
I pushed a new branch in my fork (https://github.com/yogsothoth/sqlup-mode.el/tree/feature-no-global-evals) where a new approach is taken: I get rid of the variables and rely on (looking-back ...) to do the work. It doesn't look bad.
Next step: multi-line regexp, dynamic regexps per-dialect (as was done before, more or less), and tests (using cukes, which seems very nice).

**Comment by Trevoke** [comment]
If nothing else you should bring in the most recent changes in your branch.

Also, could you provide me with a failing test for this concern over a problem when working with multiple buffers? I think maybe #56 might take care of it, but not sure.

**Comment by davidshepherd7** [comment]
This is fixed now right?

**Comment by Trevoke** [comment]
I think so; failing that, I'm sure @yogsothoth (or someone else) will reopen this if it comes back.
