### ISSUE TITLE
Test fails but behavior works. Why?

### ISSUE THREAD

**Issue by Trevoke** [Trevoke/sqlup-mode.el#49]
This test fails, but the behavior works. Why?
```cucumber
  Scenario: Upcase two keywords when typing
    Given I type "select * from -- comment"
    And I type " "
    Then I should see "SELECT * FROM -- comment"
```

**Comment by davidshepherd7** [comment]
This one is fixed by my current PR, the world makes sense again :tada: :balloon: :smile:

**Comment by Trevoke** [comment]
Ah, I see, when enabling `sql-mode` this behavior changes.

I need to consider this somewhat carefully, as based on the implementation (parsing done in a cloned buffer using`sql-mode`) I wouldn't expect that to make a difference...

**Comment by davidshepherd7** [comment]
I think there needs to be a separate set of tests for modes other than sql-mode.

Also have a look at the keywords you get when not in sql mode: they looked like a big list of strings when I expected a regex, so there might be an issue there.

**Comment by Trevoke** [comment]
Hrm. Yes, maybe. They *should* be regular expressions. Then again, `match-string` should work very well with just a bunch of strings instead of regexes.
