### ISSUE TITLE
variable name with "_" get capitalized.

### ISSUE THREAD

**Issue by adouzzy** [Trevoke/sqlup-mode.el#50]
original:
```
select max(peer_group) as peer_group
from apple
```
becomes
```
SELECT MAX(PEER_GROUP) AS PEER_GROUP
FROM apple
```

**Comment by Trevoke** [comment]
I can reproduce the problem when simply typing into emacs.

Now I just need to figure out how to write a properly failing test so I can figure out what the bug is!

**Comment by adouzzy** [comment]
One possibility is that "_" in emacs is usually treated as a symbol. But here, "_" is only a part of a word(phrase?)
