### ISSUE TITLE
Wishlist: command to do entire buffer

### ISSUE THREAD

**Issue by davidw** [Trevoke/sqlup-mode.el#67]
```
(defun sqlup-capitalize-keywords-in-buffer (start-pos end-pos)
  "Call this function on a region to capitalize the SQL keywords therein."
  (interactive "r")
  (save-excursion
    (goto-char (point-min))
    (while (< (point) (point-max))
      (sqlup-maybe-capitalize-symbol 1))))
```

Works  - maybe there's a better way.

**Comment by Trevoke** [comment]
Thank you for the request AND some sample code!

There is already a "work on region" function that you can use once you've
marked the whole buffer : `sqlup-capitalize-keywords-in-region`; if you
want to submit a PR for a function that works on the whole buffer
automatically, I have two requests:
1. Try to add a test (if you have no idea how that works, that's fine too)
2. Save the point's location before the work and restore it after the work
is done

If you're not up to submitting a PR, and you think this is a function that
should exist, let me know and I can add it when I get a little time :)

**Comment by davidw** [comment]
I'll see what I can do: my elisp skills are a bit rusty!  I know I can highlight the entire buffer and then run the region one, but one command would be even handier.

**Comment by davidw** [comment]
Doesn't `save-excursion` save the point, by the way?

**Comment by Trevoke** [comment]
Merged, thanks :)
